tools:
    Logger: Backend\Core\Utilities\Logger

subjects:
    Backend\Core\Utilities\LogMessage:
        observers:
            - Logger
            - PearLogger

# Set application settings here
application:
    values:
        mainTitle: "Backend Core"
